name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.20
commands:
  setstormtime:
    description: Establece el tiempo de la tormenta.
    usage: /<command> <segundos>
    permission: ${name}.setstormtime
  togglestorm:
    description: Activa o desactiva la tormenta.
    usage: /<command>
    permission: ${name}.togglestorm
  resetstorm:
    description: Reinicia la tormenta.
    usage: /<command>
    permission: ${name}.resetstorm
  stormstatus:
    description: Muestra el estado de la tormenta.
    usage: /<command>
    permission: ${name}.stormstatus
  setbasestormtime:
    description: Establece el tiempo base de la tormenta.
    usage: /<command> <segundos>
    permission: ${name}.setbasestormtime
  toggletotem:
    description: Activa o desactiva la mecánica de failtotem.
    usage: /<command>
    permission: ${name}.toggletotem
  setfailtotem:
    description: Ajusta el porcentaje de falla del totem.
    usage: /<command> <porcentaje>
    permission: ${name}.setfailtotem
  totemstatus:
    description: Muestra el estado actual del totem.
    usage: /<command>
    permission: ${name}.totemstatus
permissions:
  ${name}.setstormtime:
    description: Permite al jugador establecer el tiempo de la tormenta.
    default: op
  ${name}.togglestorm:
    description: Permite al jugador activar o desactivar la tormenta.
    default: op
  ${name}.resetstorm:
    description: Permite al jugador reiniciar la tormenta.
    default: op
  ${name}.stormstatus:
    description: Permite al jugador ver el estado de la tormenta.
    default: op
  ${name}.setbasestormtime:
    description: Permite al jugador establecer el tiempo base de la tormenta.
    default: op
  ${name}.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  ${name}.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  ${name}.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op