name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
api-version: 1.20
commands:
  difficulty:
    description: Comandos para ajustar la dificultad del plugin.
    usage: /<command>
    aliases: [diff]
    permission: ${name}.difficulty
permissions:
  ${name}.difficulty:
    description: Permite al jugador usar comandos de dificultad.
    default: op
  ${name}.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  ${name}.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  ${name}.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op
