name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.20
commands:
  stormtime:
    description: Establece el tiempo de la tormenta.
    usage: /<command> <segundos>
