name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.20
commands:
  setstormtime:
    description: Establece el tiempo de la tormenta.
    usage: /<command> <segundos>
    permission: ${name}.setstormtime
  togglestorm:
    description: Activa o desactiva la tormenta.
    usage: /<command>
    permission: ${name}.togglestorm
  resetstorm:
    description: Reinicia la tormenta.
    usage: /<command>
    permission: ${name}.resetstorm
  stormstatus:
    description: Muestra el estado de la tormenta.
    usage: /<command>
    permission: ${name}.stormstatus
  setbasestormtime:
    description: Establece el tiempo base de la tormenta.
    usage: /<command> <segundos>
    permission: ${name}.setbasestormtime
    
  toggletotem:
    description: Activa o desactiva la mecánica de failtotem.
    usage: /<command>
    permission: ${name}.toggletotem
  setfailtotem:
    description: Ajusta el porcentaje de falla del totem.
    usage: /<command> <porcentaje>
    permission: ${name}.setfailtotem
  totemstatus:
    description: Muestra el estado actual del totem.
    usage: /<command>
    permission: ${name}.totemstatus
    
  BeeToggle:
    description: Activa o desactiva la hostilidad de las abejas.
    usage: /<command>
    permission: ${name}.BeeToggle
  BeeSetStrength:
    description: Establece el nivel de fuerza de las abejas.
    usage: /<command> <strength>
    permission: ${name}.BeeSetStrength
  BeeStatus:
    description: Muestra el estado actual de las abejas.
    usage: /<command>
    permission: ${name}.BeeStatus

  DrownedToggleTrident:
    description: Activa o desactiva la capacidad de los ahogados para tener tridentes.
    usage: /<command>
    permission: ${name}.DrownedToggleTrident
  DrownedStatus:
    description: Muestra el estado actual de los ahogados.
    usage: /<command>
    permission: ${name}.DrownedStatus

  EndermanSetSpeed:
    description: Establece la velocidad de los endermans.
    usage: /<command> <speed>
    permission: ${name}.EndermanSetSpeed
  EndermanSetStrenght:
    description: Establece la fuerza de los endermans.
    usage: /<command> <strength>
    permission: ${name}.EndermanSetStrength
  EndermanStatus:
    description: Muestra el estado actual de los endermans.
    usage: /<command>
    permission: ${name}.EndermanStatus

  BlazeToggle:
    description: Activa o desactiva la hostilidad de los blazes.
    usage: /<command>
    permission: ${name}.BlazeToggle
  BlazeStatus:
    description: Muestra el estado actual de los blazes.
    usage: /<command>
    permission: ${name}.BlazeStatus

  CreeperSetExplosionSpeed:
    description: Establece la velocidad de explosión de los creepers.
    usage: /<command> <speed>
    permission: ${name}.CreeperSetExplosionSpeed
  CreeperStatus:
    description: Muestra el estado actual de los creepers.
    usage: /<command>
    permission: ${name}.CreeperStatus

  ElderGuardianSetResistance:
    description: Establece la resistencia de los guardianes ancianos.
    usage: /<command> <resistance>
    permission: ${name}.ElderGuardianSetResistance
  ElderGuardianStatus:
    description: Muestra el estado actual de los guardianes ancianos.
    usage: /<command>
    permission: ${name}.ElderGuardianStatus

  EndermiteToggle:
    description: Activa o desactiva la hostilidad de los endermits.
    usage: /<command>
    permission: ${name}.EndermiteToggle
  EndermiteSetStrenght:
    description: Establece la fuerza de los endermits.
    usage: /<command> <strength>
    permission: ${name}.EndermiteSetStrength
  EndermiteStatus:
    description: Muestra el estado actual de los endermits.
    usage: /<command>
    permission: ${name}.EndermiteStatus

  GhastSetExplosionPower:
    description: Establece el poder de explosión de los ghasts.
    usage: /<command> <power>
    permission: ${name}.GhastSetExplosionPower
  GhastStatus:
    description: Muestra el estado actual de los ghasts.
    usage: /<command>
    permission: ${name}.GhastStatus

  GuardianSetResistance:
    description: Establece la resistencia de los guardianes.
    usage: /<command> <resistance>
    permission: ${name}.GuardianSetResistance
  GuardianStatus:
    description: Muestra el estado actual de los guardianes.
    usage: /<command>
    permission: ${name}.GuardianStatus

  HoglinSetKnockback:
    description: Establece el knockback de los hoglins.
    usage: /<command> <knockback>
    permission: ${name}.HoglinSetKnockback
  HoglinStatus:
    description: Muestra el estado actual de los hoglins.
    usage: /<command>
    permission: ${name}.HoglinStatus

  HuskSetAxe:
    description: Establece el hacha de los husks.
    usage: /<command> <axe>
    permission: ${name}.HuskSetAxe
  HuskSetSharpness:
    description: Establece la sharpness de los husks.
    usage: /<command> <sharpness>
    permission: ${name}.HuskSetSharpness
  HuskStatus:
    description: Muestra el estado actual de los husks.
    usage: /<command>
    permission: ${name}.HuskStatus

  MagmaCubeSetKnockback:
    description: Establece el knockback de los cubos de magma.
    usage: /<command> <knockback>
    permission: ${name}.MagmaCubeSetKnockback
  MagmaCubeSetStrength:
    description: Establece la fuerza de los cubos de magma.
    usage: /<command> <strength>
    permission: ${name}.MagmaCubeSetStrength
  MagmaCubeStatus:
    description: Muestra el estado actual de los cubos de magma.
    usage: /<command>
    permission: ${name}.MagmaCubeStatus

  PhantomSetSize:
    description: Establece el tamaño de los phantoms.
    usage: /<command> <size>
    permission: ${name}.PhantomSetSize
  PhantomStatus:
    description: Muestra el estado actual de los phantoms.
    usage: /<command>
    permission: ${name}.PhantomStatus

  PiglinBruteSetSpawn:
    description: Establece la capacidad de spawneo de los piglin brutes.
    usage: /<command> <spawn>
    permission: ${name}.PiglinBruteSetSpawn
  PiglinBruteStatus:
    description: Muestra el estado actual de los piglin brutes.
    usage: /<command>
    permission: ${name}.PiglinBruteStatus

permissions:
  ${name}.setstormtime:
    description: Permite al jugador establecer el tiempo de la tormenta.
    default: op
  ${name}.togglestorm:
    description: Permite al jugador activar o desactivar la tormenta.
    default: op
  ${name}.resetstorm:
    description: Permite al jugador reiniciar la tormenta.
    default: op
  ${name}.stormstatus:
    description: Permite al jugador ver el estado de la tormenta.
    default: op
  ${name}.setbasestormtime:
    description: Permite al jugador establecer el tiempo base de la tormenta.
    default: op

  ${name}.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  ${name}.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  ${name}.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op
    
  ${name}.BeeToggle:
    description: Permite al jugador activar o desactivar la hostilidad de las abejas.
    default: op
  ${name}.BeeSetStrength:
    description: Permite al jugador establecer la fuerza de las abejas.
    default: op
  ${name}.BeeStatus:
    description: Permite al jugador ver el estado actual de las abejas.
    default: op

  ${name}.DrownedToggleTrident:
    description: Permite al jugador activar o desactivar la capacidad de los ahogados para lanzar tridentes.
    default: op
  ${name}.DrownedStatus:
    description: Permite al jugador ver el estado actual de los ahogados.
    default: op

  ${name}.EndermanSetSpeed:
    description: Permite al jugador establecer la velocidad de los endermans.
    default: op
  ${name}.EndermanSetStrength:
    description: Permite al jugador establecer la fuerza de los endermans.
    default: op
  ${name}.EndermanStatus:
    description: Permite al jugador ver el estado actual de los endermans.
    default: op

  ${name}.BlazeToggle:
    description: Permite al jugador activar o desactivar la hostilidad de los blazes.
    default: op
  ${name}.BlazeStatus:
    description: Permite al jugador ver el estado actual de los blazes.
    default: op

  ${name}.CreeperSetExplosionSpeed:
    description: Permite al jugador establecer la velocidad de explosión de los creepers.
    default: op
  ${name}.CreeperStatus:
    description: Permite al jugador ver el estado actual de los creepers.
    default: op

  ${name}.ElderGuardianSetResistance:
    description: Permite al jugador establecer la resistencia de los guardianes ancianos.
    default: op
  ${name}.ElderGuardianStatus:
    description: Permite al jugador ver el estado actual de los guardianes ancianos.
    default: op

  ${name}.EndermiteToggle:
    description: Permite al jugador activar o desactivar la hostilidad de los endermits.
    default: op
  ${name}.EndermiteSetStrength:
    description: Permite al jugador establecer la fuerza de los endermits.
    default: op
  ${name}.EndermiteStatus:
    description: Permite al jugador ver el estado actual de los endermits.
    default: op

  ${name}.GhastSetExplosionPower:
    description: Permite al jugador establecer el poder de explosión de los ghasts.
    default: op
  ${name}.GhastStatus:
    description: Permite al jugador ver el estado actual de los ghasts.
    default: op

  ${name}.GuardianSetResistance:
    description: Permite al jugador establecer la resistencia de los guardianes.
    default: op
  ${name}.GuardianStatus:
    description: Permite al jugador ver el estado actual de los guardianes.
    default: op

  ${name}.HoglinSetKnockback:
    description: Permite al jugador establecer el knockback de los hoglins.
    default: op
  ${name}.HoglinStatus:
    description: Permite al jugador ver el estado actual de los hoglins.
    default: op

  ${name}.HuskSetAxe:
    description: Permite al jugador establecer el hacha de los husks.
    default: op
  ${name}.HuskSetSharpness:
    description: Permite al jugador establecer la sharpness de los husks.
    default: op
  ${name}.HuskStatus:
    description: Permite al jugador ver el estado actual de los husks.
    default: op

  ${name}.MagmaCubeSetKnockback:
    description: Permite al jugador establecer el knockback de los cubos de magma.
    default: op
  ${name}.MagmaCubeSetStrength:
    description: Permite al jugador establecer la fuerza de los cubos de magma.
    default: op
  ${name}.MagmaCubeStatus:
    description: Permite al jugador ver el estado actual de los cubos de magma.
    default: op

  ${name}.PhantomSetSize:
    description: Permite al jugador establecer el tamaño de los phantoms.
    default: op
  ${name}.PhantomStatus:
    description: Permite al jugador ver el estado actual de los phantoms.
    default: op

  ${name}.PiglinBruteSetSpawn:
    description: Permite al jugador establecer la capacidad de spawneo de los piglin brutes.
    default: op
  ${name}.PiglinBruteStatus:
    description: Permite al jugador ver el estado actual de los piglin brutes.
    default: op