name: PluginDifficulty
description: This plugin is created for the Insomnia
author: ewahv1
main: me.ewahv1.plugin.Main
version: 0.0.1
url: https://github.com/2lstudios-mc/bukkit-boilerplate
api-version: 1.20
commands:
  setstormtime:
    description: Establece el tiempo de la tormenta.
    usage: /<command> <segundos>
    permission: PluginDifficulty.setstormtime
  togglestorm:
    description: Activa o desactiva la tormenta.
    usage: /<command>
    permission: PluginDifficulty.togglestorm
  resetstorm:
    description: Reinicia la tormenta.
    usage: /<command>
    permission: PluginDifficulty.resetstorm
  stormstatus:
    description: Muestra el estado de la tormenta.
    usage: /<command>
    permission: PluginDifficulty.stormstatus
  setbasestormtime:
    description: Establece el tiempo base de la tormenta.
    usage: /<command> <segundos>
    permission: PluginDifficulty.setbasestormtime
  toggletotem:
    description: Activa o desactiva la mecánica de failtotem.
    usage: /<command>
    permission: PluginDifficulty.toggletotem
  setfailtotem:
    description: Ajusta el porcentaje de falla del totem.
    usage: /<command> <porcentaje>
    permission: PluginDifficulty.setfailtotem
  totemstatus:
    description: Muestra el estado actual del totem.
    usage: /<command>
    permission: PluginDifficulty.totemstatus
  toggleblaze:
    description: Cambia el estado de inmunidad de los Blazes.
    usage: /<command>
    permission: PluginDifficulty.toggleblaze
  blazestatus:
    description: Muestra el estado de inmunidad de los Blazes.
    usage: /<command>
    permission: PluginDifficulty.blazestatus
  setbeehostility:
    description: Establece la hostilidad de las abejas.
    usage: /<command> <true|false>
    permission: PluginDifficulty.setbeehostility
  setbeestrength:
    description: Establece la fuerza de las abejas.
    usage: /<command> <strength>
    permission: PluginDifficulty.setbeestrength
  setcreeperexplosionspeed:
    description: Establece la velocidad de explosión de los Creepers.
    usage: /<command> <speed>
    permission: PluginDifficulty.setcreeperexplosionspeed
  setelderguardianresistance:
    description: Establece la resistencia del Elder Guardian.
    usage: /<command> <resistance>
    permission: PluginDifficulty.setelderguardianresistance
  setdrownedtrident:
    description: Establece si los Drowned tienen un tridente.
    usage: /<command> <true|false>
    permission: PluginDifficulty.setdrownedtrident
  setdrownedchanneling:
    description: Establece el nivel de channeling del tridente de los Drowned.
    usage: /<command> <level>
    permission: PluginDifficulty.setdrownedchanneling
  setendermanspeed:
    description: Establece la velocidad del Enderman.
    usage: /<command> <speed>
    permission: PluginDifficulty.setendermanspeed
  setendermanstrength:
    description: Establece la fuerza del Enderman.
    usage: /<command> <strength>
    permission: PluginDifficulty.setendermanstrength
  setendermiteinvulnerability:
    description: Establece la invulnerabilidad del Endermite.
    usage: /<command> <true|false>
    permission: PluginDifficulty.setendermiteinvulnerability
  setendermitestrength:
    description: Establece la fuerza del Endermite.
    usage: /<command> <strength>
    permission: PluginDifficulty.setendermitestrength
  setghastexplosionpower:
    description: Establece el poder de explosión del Ghast.
    usage: /<command> <power>
    permission: PluginDifficulty.setghastexplosionpower
  setguardianresistance:
    description: Establece la resistencia del Guardian.
    usage: /<command> <resistance>
    permission: PluginDifficulty.setguardianresistance
  sethoglinknockback:
    description: Establece el empuje hacia atrás del Hoglin.
    usage: /<command> <knockback>
    permission: PluginDifficulty.sethoglinknockback
  sethuskaxe:
    description: Establece el tipo de hacha del Husk.
    usage: /<command> <axe>
    permission: PluginDifficulty.sethuskaxe
  sethusksharpness:
    description: Establece la nitidez del hacha del Husk.
    usage: /<command> <sharpness>
    permission: PluginDifficulty.sethusksharpness
  setmagmacubeknockback:
    description: Establece el empuje hacia atrás del MagmaCube.
    usage: /<command> <knockback>
    permission: PluginDifficulty.setmagmacubeknockback
  setmagmacubestrength:
    description: Establece la fuerza del MagmaCube.
    usage: /<command> <strength>
    permission: PluginDifficulty.setmagmacubestrength
  setphantomsize:
    description: Establece el tamaño del Phantom.
    usage: /<command> <size>
    permission: PluginDifficulty.setphantomsize
  setpiglinbrutespawn:
    description: Establece el spawn del PiglinBrute.
    usage: /<command> <spawn>
    permission: PluginDifficulty.setpiglinbrutespawn
permissions:
  PluginDifficulty.setstormtime:
    description: Permite al jugador establecer el tiempo de la tormenta.
    default: op
  PluginDifficulty.togglestorm:
    description: Permite al jugador activar o desactivar la tormenta.
    default: op
  PluginDifficulty.resetstorm:
    description: Permite al jugador reiniciar la tormenta.
    default: op
  PluginDifficulty.stormstatus:
    description: Permite al jugador ver el estado de la tormenta.
    default: op
  PluginDifficulty.setbasestormtime:
    description: Permite al jugador establecer el tiempo base de la tormenta.
    default: op
  PluginDifficulty.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  PluginDifficulty.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  PluginDifficulty.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op
  PluginDifficulty.toggleblaze:
    description: Permite al jugador cambiar el estado de inmunidad de los Blazes.
    default: op
  PluginDifficulty.blazestatus:
    description: Permite al jugador ver el estado de inmunidad de los Blazes.
    default: op
  PluginDifficulty.setbeehostility:
    description: Permite al jugador establecer la hostilidad de las abejas.
    default: op
  PluginDifficulty.setbeestrength:
    description: Permite al jugador establecer la fuerza de las abejas.
    default: op
  PluginDifficulty.setcreeperexplosionspeed:
    description: Permite al jugador establecer la velocidad de explosión de los Creepers.
    default: op
  PluginDifficulty.setelderguardianresistance:
    description: Permite al jugador establecer la resistencia del Elder Guardian.
    default: op
  PluginDifficulty.setdrownedtrident:
    description: Permite al jugador establecer si los Drowned tienen un tridente.
    default: op
  PluginDifficulty.setdrownedchanneling:
    description: Permite al jugador establecer el nivel de channeling del tridente de los Drowned.
    default: op
  PluginDifficulty.setendermanspeed:
    description: Permite al jugador establecer la velocidad del Enderman.
    default: op
  PluginDifficulty.setendermanstrength:
    description: Permite al jugador establecer la fuerza del Enderman.
    default: op
  PluginDifficulty.setendermiteinvulnerability:
    description: Permite al jugador establecer la invulnerabilidad del Endermite.
    default: op
  PluginDifficulty.setendermitestrength:
    description: Permite al jugador establecer la fuerza del Endermite.
    default: op
  PluginDifficulty.setghastexplosionpower:
    description: Permite al jugador establecer el poder de explosión del Ghast.
    default: op
  PluginDifficulty.setguardianresistance:
    description: Permite al jugador establecer la resistencia del Guardian.
    default: op
  PluginDifficulty.sethoglinknockback:
    description: Permite al jugador establecer el empuje hacia atrás del Hoglin.
    default: op
  PluginDifficulty.sethuskaxe:
    description: Permite al jugador establecer el tipo de hacha del Husk.
    default: op
  PluginDifficulty.sethusksharpness:
    description: Permite al jugador establecer la nitidez del hacha del Husk.
    default: op
  PluginDifficulty.setmagmacubeknockback:
    description: Permite al jugador establecer el empuje hacia atrás del MagmaCube.
    default: op
  PluginDifficulty.setmagmacubestrength:
    description: Permite al jugador establecer la fuerza del MagmaCube.
    default: op
  PluginDifficulty.setphantomsize:
    description: Permite al jugador establecer el tamaño del Phantom.
    default: op
  PluginDifficulty.setpiglinbrutespawn:
    description: Permite al jugador establecer el spawn del PiglinBrute.
    default: op