name: PluginDifficulty
description: This plugin is created for the Insomnia
author: ewahv1
main: me.ewahv1.plugin.Main
version: 0.0.1
api-version: 1.20
commands:
  setstormtime:
    description: Establece el tiempo de la tormenta.
    usage: /<command> <segundos>
    permission: PluginDifficulty.setstormtime
  togglestorm:
    description: Activa o desactiva la tormenta.
    usage: /<command>
    permission: PluginDifficulty.togglestorm
  resetstorm:
    description: Reinicia la tormenta.
    usage: /<command>
    permission: PluginDifficulty.resetstorm
  stormstatus:
    description: Muestra el estado de la tormenta.
    usage: /<command>
    permission: PluginDifficulty.stormstatus
  setbasestormtime:
    description: Establece el tiempo base de la tormenta.
    usage: /<command> <segundos>
    permission: PluginDifficulty.setbasestormtime
  toggletotem:
    description: Activa o desactiva la mecánica de failtotem.
    usage: /<command>
    permission: PluginDifficulty.toggletotem
  setfailtotem:
    description: Ajusta el porcentaje de falla del totem.
    usage: /<command> <porcentaje>
    permission: PluginDifficulty.setfailtotem
  totemstatus:
    description: Muestra el estado actual del totem.
    usage: /<command>
    permission: PluginDifficulty.totemstatus
  BeeToggle:
    description: Establece la hostilidad de las abejas.
    usage: /<command>
    permission: PluginDifficulty.BeeToggle
  BeeSetStrength:
    description: Establece el nivel de fuerza de las abejas.
    usage: /<command> <strength>
    permission: PluginDifficulty.BeeSetStrength
  BeeStatus:
    description: Muestra el estado actual de las abejas.
    usage: /<command>
    permission: PluginDifficulty.BeeStatus
  DrownedToggleTrident:
    description: Establece si los ahogados tienen un tridente.
    usage: /<command>
    permission: PluginDifficulty.DrownedToggleTrident
  DrownedStatus:
    description: Muestra el estado actual de los ahogados.
    usage: /<command>
    permission: PluginDifficulty.DrownedStatus
  EndermanSetSpeed:
    description: Establece la velocidad de los endermans.
    usage: /<command> <speed>
    permission: PluginDifficulty.EndermanSetSpeed
  EndermanSetStrength:
    description: Establece la fuerza de los endermans.
    usage: /<command> <strength>
    permission: PluginDifficulty.EndermanSetStrength
  EndermanStatus:
    description: Muestra el estado actual de los endermans.
    usage: /<command>
    permission: PluginDifficulty.EndermanStatus
  BlazeToggle:
    description: Establece la hostilidad de los blazes.
    usage: /<command>
    permission: PluginDifficulty.BlazeToggle
  BlazeStatus:
    description: Muestra el estado actual de los blazes.
    usage: /<command>
    permission: PluginDifficulty.BlazeStatus
  CreeperSetExplosionSpeed:
    description: Establece la velocidad de explosión de los creepers.
    usage: /<command> <speed>
    permission: PluginDifficulty.CreeperSetExplosionSpeed
  CreeperStatus:
    description: Muestra el estado actual de los creepers.
    usage: /<command>
    permission: PluginDifficulty.CreeperStatus
  ElderGuardianSetResistance:
    description: Establece la resistencia de los guardianes ancianos.
    usage: /<command> <resistance>
    permission: PluginDifficulty.ElderGuardianSetResistance
  ElderGuardianStatus:
    description: Muestra el estado actual de los guardianes ancianos.
    usage: /<command>
    permission: PluginDifficulty.ElderGuardianStatus
  EndermiteToggle:
    description: Establece la hostilidad de los endermits.
    usage: /<command>
    permission: PluginDifficulty.EndermiteToggle
  EndermiteSetStrength:
    description: Establece la fuerza de los endermits.
    usage: /<command> <strength>
    permission: PluginDifficulty.EndermiteSetStrength
  EndermiteStatus:
    description: Muestra el estado actual de los endermits.
    usage: /<command>
    permission: PluginDifficulty.EndermiteStatus
  GhastSetExplosionPower:
    description: Establece el poder de explosión de los ghasts.
    usage: /<command> <power>
    permission: PluginDifficulty.GhastSetExplosionPower
  GhastStatus:
    description: Muestra el estado actual de los ghasts.
    usage: /<command>
    permission: PluginDifficulty.GhastStatus
  GuardianSetResistance:
    description: Establece la resistencia de los guardianes.
    usage: /<command> <resistance>
    permission: PluginDifficulty.GuardianSetResistance
  GuardianStatus:
    description: Muestra el estado actual de los guardianes.
    usage: /<command>
    permission: PluginDifficulty.GuardianStatus
  HoglinSetKnockback:
    description: Establece el knockback de los hoglins.
    usage: /<command> <knockback>
    permission: PluginDifficulty.HoglinSetKnockback
  HoglinStatus:
    description: Muestra el estado actual de los hoglins.
    usage: /<command>
    permission: PluginDifficulty.HoglinStatus
  HuskSetAxe:
    description: Establece el hacha de los husks.
    usage: /<command> <axe>
    permission: PluginDifficulty.HuskSetAxe
  HuskSetSharpness:
    description: Establece el sharpness de los husks.
    usage: /<command> <sharpness>
    permission: PluginDifficulty.HuskSetSharpness
  HuskStatus:
    description: Muestra el estado actual de los husks.
    usage: /<command>
    permission: PluginDifficulty.HuskStatus
  IronGolemToggle:
    description: Cambia la resistencia al fuego del Iron Golem.
    usage: /<command>
    permission: PluginDifficulty.IronGolemToggle
  IronGolemStatus:
    description: Muestra el estado de la resistencia al fuego del Iron Golem.
    usage: /<command>
    permission: PluginDifficulty.IronGolemStatus
  MagmaCubeSetKnockback:
    description: Establece el knockback de los cubos de magma.
    usage: /<command> <knockback>
    permission: PluginDifficulty.MagmaCubeSetKnockback
  MagmaCubeSetStrength:
    description: Establece la fuerza de los cubos de magma.
    usage: /<command> <strength>
    permission: PluginDifficulty.MagmaCubeSetStrength
  MagmaCubeStatus:
    description: Muestra el estado actual de los cubos de magma.
    usage: /<command>
    permission: PluginDifficulty.MagmaCubeStatus
  PhantomSetSize:
    description: Establece el tamaño de los phantoms.
    usage: /<command> <size>
    permission: PluginDifficulty.PhantomSetSize
  PhantomStatus:
    description: Muestra el estado actual de los phantoms.
    usage: /<command>
    permission: PluginDifficulty.PhantomStatus
  PiglinBruteSetSpawn:
    description: Establece la capacidad de spawneo de los piglin brutes.
    usage: /<command> <spawn>
    permission: PluginDifficulty.PiglinBruteSetSpawn
  PiglinBruteStatus:
    description: Muestra el estado actual de los piglin brutes.
    usage: /<command>
    permission: PluginDifficulty.PiglinBruteStatus
  PiglinSetSwordMaterial:
    description: Establece el material de la espada del Piglin.
    usage: /<command> <material>
    permission: PluginDifficulty.PiglinSetSwordMaterial
  PiglinSetQuickCharge:
    description: Establece el nivel de Quick Charge de la ballesta del Piglin.
    usage: /<command> <nivel>
    permission: PluginDifficulty.PiglinSetQuickCharge
  PiglinStatus:
    description: Muestra el estado actual del Piglin.
    usage: /<command>
    permission: PluginDifficulty.PiglinStatus
  PillagerSetDamage:
    description: Establece el multiplicador de daño del Pillager.
    usage: /<command> <multiplicador>
    permission: PluginDifficulty.PillagerSetDamage
  PillagerSetCriticalPorcentage:
    description: Establece el porcentaje crítico del Pillager.
    usage: /<command> <porcentaje>
    permission: PluginDifficulty.PillagerSetCriticalPorcentage
  PillagerSetInstantDamageArrow:
    description: Establece el daño instantáneo de la flecha del Pillager.
    usage: /<command> <daño>
    permission: PluginDifficulty.PillagerSetInstantDamageArrow
  PillagerStatus:
    description: Muestra el estado actual del Pillager.
    usage: /<command>
    permission: PluginDifficulty.PillagerStatus
  ZombifiedPiglinSetSpeed:
    description: Establece la velocidad del Zombified Piglin.
    usage: /<command> <velocidad>
    permission: PluginDifficulty.ZombifiedPiglinSetSpeed
  ZombifiedPiglinToggle:
    description: Cambia el arma del Zombified Piglin.
    usage: /<command>
    permission: PluginDifficulty.ZombifiedPiglinToggle
  ZombifiedPiglinSetFireAspect:
    description: Establece el nivel de Fire Aspect de la Blaze Rod del Zombified Piglin.
    usage: /<command> <nivel>
    permission: PluginDifficulty.ZombifiedPiglinSetFireAspect
  ZombifiedPiglinStatus:
    description: Muestra el estado actual del Zombified Piglin.
    usage: /<command>
    permission: PluginDifficulty.ZombifiedPiglinStatus
permissions:
  PluginDifficulty.setstormtime:
    description: Permite al jugador establecer el tiempo de la tormenta.
    default: op
  PluginDifficulty.togglestorm:
    description: Permite al jugador activar o desactivar la tormenta.
    default: op
  PluginDifficulty.resetstorm:
    description: Permite al jugador reiniciar la tormenta.
    default: op
  PluginDifficulty.stormstatus:
    description: Permite al jugador ver el estado de la tormenta.
    default: op
  PluginDifficulty.setbasestormtime:
    description: Permite al jugador establecer el tiempo base de la tormenta.
    default: op
  PluginDifficulty.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  PluginDifficulty.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  PluginDifficulty.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op
  PluginDifficulty.BeeToggle:
    description: Permite al jugador establecer la hostilidad de las abejas.
    default: op
  PluginDifficulty.BeeSetStrength:
    description: Permite al jugador establecer el nivel de fuerza de las abejas.
    default: op
  PluginDifficulty.BeeStatus:
    description: Permite al jugador ver el estado actual de las abejas.
    default: op
  PluginDifficulty.DrownedToggleTrident:
    description: Permite al jugador establecer si los ahogados tienen un tridente.
    default: op
  PluginDifficulty.DrownedStatus:
    description: Permite al jugador ver el estado actual de los ahogados.
    default: op
  PluginDifficulty.EndermanSetSpeed:
    description: Permite al jugador establecer la velocidad de los endermans.
    default: op
  PluginDifficulty.EndermanSetStrength:
    description: Permite al jugador establecer la fuerza de los endermans.
    default: op
  PluginDifficulty.EndermanStatus:
    description: Permite al jugador ver el estado actual de los endermans.
    default: op
  PluginDifficulty.BlazeToggle:
    description: Permite al jugador establecer la hostilidad de los blazes.
    default: op
  PluginDifficulty.BlazeStatus:
    description: Permite al jugador ver el estado actual de los blazes.
    default: op
  PluginDifficulty.CreeperSetExplosionSpeed:
    description: Permite al jugador establecer la velocidad de explosión de los creepers.
    default: op
  PluginDifficulty.CreeperStatus:
    description: Permite al jugador ver el estado actual de los creepers.
    default: op
  PluginDifficulty.ElderGuardianSetResistance:
    description: Permite al jugador establecer la resistencia de los guardianes ancianos.
    default: op
  PluginDifficulty.ElderGuardianStatus:
    description: Permite al jugador ver el estado actual de los guardianes ancianos.
    default: op
  PluginDifficulty.EndermiteToggle:
    description: Permite al jugador establecer la hostilidad de los endermits.
    default: op
  PluginDifficulty.EndermiteSetStrength:
    description: Permite al jugador establecer la fuerza de los endermits.
    default: op
  PluginDifficulty.EndermiteStatus:
    description: Permite al jugador ver el estado actual de los endermits.
    default: op
  PluginDifficulty.GhastSetExplosionPower:
    description: Permite al jugador establecer el poder de explosión de los ghasts.
    default: op
  PluginDifficulty.GhastStatus:
    description: Permite al jugador ver el estado actual de los ghasts.
    default: op
  PluginDifficulty.GuardianSetResistance:
    description: Permite al jugador establecer la resistencia de los guardianes.
    default: op
  PluginDifficulty.GuardianStatus:
    description: Permite al jugador ver el estado actual de los guardianes.
    default: op
  PluginDifficulty.HoglinSetKnockback:
    description: Permite al jugador establecer el knockback de los hoglins.
    default: op
  PluginDifficulty.HoglinStatus:
    description: Permite al jugador ver el estado actual de los hoglins.
    default: op
  PluginDifficulty.HuskSetAxe:
    description: Permite al jugador establecer el hacha de los husks.
    default: op
  PluginDifficulty.HuskSetSharpness:
    description: Permite al jugador establecer el sharpness de los husks.
    default: op
  PluginDifficulty.HuskStatus:
    description: Permite al jugador ver el estado actual de los husks.
    default: op
  PluginDifficulty.IronGolemToggle:
    description: Permite al jugador cambiar la resistencia al fuego del Iron Golem.
    default: op
  PluginDifficulty.IronGolemStatus:
    description: Permite al jugador ver el estado de la resistencia al fuego del Iron Golem.
    default: op
  PluginDifficulty.MagmaCubeSetKnockback:
    description: Permite al jugador establecer el knockback de los cubos de magma.
    default: op
  PluginDifficulty.MagmaCubeSetStrength:
    description: Permite al jugador establecer la fuerza de los cubos de magma.
    default: op
  PluginDifficulty.MagmaCubeStatus:
    description: Permite al jugador ver el estado actual de los cubos de magma.
    default: op
  PluginDifficulty.PhantomSetSize:
    description: Permite al jugador establecer el tamaño de los phantoms.
    default: op
  PluginDifficulty.PhantomStatus:
    description: Permite al jugador ver el estado actual de los phantoms.
    default: op
  PluginDifficulty.PiglinBruteSetSpawn:
    description: Permite al jugador establecer la capacidad de spawneo de los piglin brutes.
    default: op
  PluginDifficulty.PiglinBruteStatus:
    description: Permite al jugador ver el estado actual de los piglin brutes.
    default: op
  PluginDifficulty.PiglinSetSwordMaterial:
    description: Permite al jugador establecer el material de la espada del Piglin.
    default: op
  PluginDifficulty.PiglinSetQuickCharge:
    description: Permite al jugador establecer el nivel de Quick Charge de la ballesta del Piglin.
    default: op
  PluginDifficulty.PiglinStatus:
    description: Permite al jugador ver el estado actual del Piglin.
    default: op
  PluginDifficulty.PillagerSetDamage:
    description: Permite al jugador etablecer la la cantidad de daño que hacen los pillager
    default: op
  PluginDifficulty.PillagerSetDamage:
    description: Permite al jugador establecer el multiplicador de daño del Pillager.
    default: op
  PluginDifficulty.PillagerSetCriticalPorcentage:
    description: Permite al jugador establecer el porcentaje crítico del Pillager.
    default: op
  PluginDifficulty.PillagerSetInstantDamageArrow:
    description: Permite al jugador establecer el daño instantáneo de la flecha del Pillager.
    default: op
  PluginDifficulty.PillagerStatus:
    description: Permite al jugador ver el estado actual del Pillager.
    default: op
  PluginDifficulty.ZombifiedPiglinSetSpeed:
    description: Permite al jugador establecer la velocidad del Zombified Piglin.
    default: op
  PluginDifficulty.ZombifiedPiglinToggle:
    description: Permite al jugador cambiar el arma del Zombified Piglin.
    default: op
  PluginDifficulty.ZombifiedPiglinSetFireAspect:
    description: Permite al jugador establecer el nivel de Fire Aspect de la Blaze Rod del Zombified Piglin.
    default: op
  PluginDifficulty.ZombifiedPiglinStatus:
    description: Permite al jugador ver el estado actual del Zombified Piglin.
    default: op