name: DifficultyPlugin
description: This plugin is created for the Insomnia
author: ewahv1
main: me.ewahv1.plugin.Main
version: 0.0.1
api-version: 1.20
commands:
  toggletotem:
    description: Activa o desactiva la mecánica de failtotem.
    usage: /<command>
    permission: DifficultyPlugin.toggletotem
  setfailtotem:
    description: Ajusta el porcentaje de falla del totem.
    usage: /<command> <porcentaje>
    permission: DifficultyPlugin.setfailtotem
  totemstatus:
    description: Muestra el estado actual del totem.
    usage: /<command>
    permission: DifficultyPlugin.totemstatus
permissions:
  DifficultyPlugin.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  DifficultyPlugin.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  DifficultyPlugin.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op