name: PluginInsomnia
description: This plugin is created for the Insomnia
author: ewahv1
main: me.ewahv1.plugin.Main
version: 0.0.1
api-version: 1.20
commands:
  setstormtime:
    description: Establece el tiempo de la tormenta.
    usage: /<command> <segundos>
    permission: PluginInsomnia.setstormtime
  togglestorm:
    description: Activa o desactiva la tormenta.
    usage: /<command>
    permission: PluginInsomnia.togglestorm
  resetstorm:
    description: Reinicia la tormenta.
    usage: /<command>
    permission: PluginInsomnia.resetstorm
  stormstatus:
    description: Muestra el estado de la tormenta.
    usage: /<command>
    permission: PluginInsomnia.stormstatus
  setbasestormtime:
    description: Establece el tiempo base de la tormenta.
    usage: /<command> <segundos>
    permission: PluginInsomnia.setbasestormtime
  toggletotem:
    description: Activa o desactiva la mecánica de failtotem.
    usage: /<command>
    permission: PluginInsomnia.toggletotem
  setfailtotem:
    description: Ajusta el porcentaje de falla del totem.
    usage: /<command> <porcentaje>
    permission: PluginInsomnia.setfailtotem
  totemstatus:
    description: Muestra el estado actual del totem.
    usage: /<command>
    permission: PluginInsomnia.totemstatus
permissions:
  PluginInsomnia.setstormtime:
    description: Permite al jugador establecer el tiempo de la tormenta.
    default: op
  PluginInsomnia.togglestorm:
    description: Permite al jugador activar o desactivar la tormenta.
    default: op
  PluginInsomnia.resetstorm:
    description: Permite al jugador reiniciar la tormenta.
    default: op
  PluginInsomnia.stormstatus:
    description: Permite al jugador ver el estado de la tormenta.
    default: op
  PluginInsomnia.setbasestormtime:
    description: Permite al jugador establecer el tiempo base de la tormenta.
    default: op
  PluginInsomnia.toggletotem:
    description: Permite al jugador activar o desactivar la mecánica de failtotem.
    default: op
  PluginInsomnia.setfailtotem:
    description: Permite al jugador ajustar el porcentaje de falla del totem.
    default: op
  PluginInsomnia.totemstatus:
    description: Permite al jugador ver el estado actual del totem.
    default: op